server:
  port: 8090
  
spring:
  application:
    name: FRUITS-STORE
  datasource: 
    url: jdbc:postgresql://localhost:5460/postgres
    username: postgres
    password: 123456
    
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: none
    properties: 
      hiberbate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_shema: fruitsStore
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: ERROR
  file:
    name: logs/fruits_store.log
    
    
    
    
    
    
    